### PR TITLE
added Samtec LSHM series connectors

### PR DESCRIPTION
**Pull request by ashtonchase**
Connector PDF
http://suddendocs.samtec.com/catalog_english/lshm_dv.pdf

Footprint PDF
http://suddendocs.samtec.com/prints/lshm-1xx-xx.x-x-dv-a-x-x-tr-footprint.pdf

Original Pull Request in Connectors.pretty
https://github.com/KiCad/Connect.pretty/pull/37

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Ashton,

I had a look at your footprints. First, the documents you linked are about the DV variant whereas the ones you added are the DC one. Are they the same?

If so, it seems the DC-A-N connectors need fixing. According to the doc, the length of the connector is the number of positions \* 0.5 + 4.95. For the 100-pin connector, this makes 29.95 and this is not accounting for the small clips on either side. Their thickness doesn't seem documented so I'd add 0.5mm on each side for them. I'm looking at your footprint and the courtyard width is 29.5mm, so clearly not enough. The silkscreen is thus also wrong. Its outline must be completely visible after board assembly as per rule 6.5 and as it stands now it will be hidden.

Please make sure the DC-A-S is also correct.

Thanks!

**Comment by CarlPoirier** [comment]
Did you mean to replace the *-DC-A-N parts by the *-DV-A-N ones? If so, they are still part of the pull request.

I had a look at the new footprints. The ones for the connectors without shield are great, but please double check the dimensions for the connectors with shield.

Finally, the name has two XX in extra. For example, LSHM-1XX-XX.X-X-DV-A-X should yield LSHM-120-XX.X-X-DV whereas you have LSHM-120-xx-xxx-x-DV. Also, you can keep the period in there.

Regards,

Carl

**Comment by ashtonchase** [comment]
Hi @CarlPoirier,

I have cleared the old 'DC' connectors and renamed all spots accordingly. 

**Regarding the period**. I had to take the period out early on because KiCAD would not recognize the 3D models with periods in the file names. 

**Regarding the shielded connectors**. I stand by the dimensions for those connections. In your message earlier you used the formula for the shield connectors, not the un-shielded.

For shielded, it's number of positions \* 0.5 + 4.95
For unshielded, it's number of positions \* 0.5 + 2.00

image

This is also confirmed by referring to [PCB footprint PDF](http://suddendocs.samtec.com/prints/lshm-1xx-xx.x-x-dv-a-x-x-tr-footprint.pdf)

This is visible as well viewing the 3D models.

**Comment by CarlPoirier** [comment]
Okay, that's great for the period. As for the shielded connectors dimensions, I was looking at the "D" measurement in the footprint pdf. I guess it is a little bit bigger because it includes the clipping tabs on each side. I'm merging it! Thanks for your contribution.

**Pull request merged**
