### PR TITLE
Create MECF-08-01-L-DV-WT.kicad_mod

### PR DESCRIPTION
**Pull request by Matyro**
Samtec MECF 14 Pin Connector

https://www.samtec.com/products/mecf-dv

samtec

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matyro how are your Python programming skills? 

This entire set of footprints would be a great addition to the library. We use the [kicad-footprint-generator](https://github.com/pointhi/kicad-footprint-generator) scripts for repetitive footprints - this would be a great candidate.

If you are willing, the entire series could be added, instead of a single one :)

**Comment by Matyro** [comment]
Python should be fine, i will look into it

Should i put the connector side open pads on booth pcb sides into the samtec lib as well?

**Comment by SchrodingersGat** [comment]
> Should i put the connector side open pads on booth pcb sides into the samtec lib as well?

Sorry I'm not sure what you mean here...

**Comment by Matyro** [comment]
The Samtec parts are only sockets you plug in the edge of another pcb. The question is if the edge part of the pcb should be included as a footprint in this pretty library.

**Comment by SchrodingersGat** [comment]
Yes, that would be useful :) If this is a PCB-only footprint (no connector) then we will have to decide what to call them.

**Comment by Matyro** [comment]
I would call them MECF-08-01-L-DV-WT_socket and MECF-08-01-L-DV-WT_edgeconnect or connector

**Comment by Matyro** [comment]
I have finished the script should i upload it here?
Here are 2 images of the 80 different footprints

One yellow line at the connector is on the Edge.Cuts layer

Should i move the connector or can it stay of center?

connector
socket

**Comment by Matyro** [comment]
connector
I think the foodprints are ok now.

The autocheck has problems with the center, the main reason for this that I don't offset the bottom lines. Each line ends with the end of the board and not with the offset normally applied.

**Comment by SchrodingersGat** [comment]
A few issues here:

a) The courtyards for the MECF_xxx_Socket connectors are rotated by 90 degrees:
a

b) for pins that do not have an associated number, set these to "" (empty string) instead of "None"
c) Please use suffix "_Edge" instead of "_Connector" for the PCB-side footprints
d) Don't place any "edge cut" lines into the actual footprint. You could put a horizontal line on User.Drawings perhaps but the edge cut should be reserved for the PCB.
e) Please rearrange the RefDes and Value text items as follows:
   i. RefDes on silkscreen should NOT be over pads
   ii. RefDes on silkscreen should be outside the footprint
   iii. Move Value and F.Fab RefDes inside the footprints.
b
f) For the _Edge connectors, ensure these are marked as "Virtual" (they do not have an associated component to be placed:

c

**Comment by Matyro** [comment]
> Don't place any "edge cut" lines into the actual footprint. You could put a horizontal line on User.Drawings perhaps but the edge cut should be reserved for the PCB.

There is only a limited margin of errors for this connector and i find it very hard for the user to specify the necessary cutouts and borders without the exact pad position or a script. When there is room for discussion I would like to suggest keeping this layer in the footprint.

**Comment by Matyro** [comment]
I added all changes to my scripts except the removal of the edge cut layer. It should mark exaclty where to cut the pcb because it must fit in the socket similar to a PCI Port on a graphics cart.

**Comment by evanshultz** [comment]
@SchrodingersGat You were the reviewer for this PR. Can you please take a look at the outstanding question above about the cutout?

I agree that the cutout should be part of this footprint. Without the cutout the connector won't fit, and trying to exactly place the cutout once the footprint is placed on a board is far less easy that having all the pieces to make the connector fit as part of the footprint.

**Comment by SchrodingersGat** [comment]
@matyro @evanshultz yes I see now what you mean, this is probably a very good idea. 

I have spotted a couple of errors with the edge-cuts though. See the image below - the edge cuts in some cases cross over and will not form correct corners.

screenshot from 2017-06-22 19-05-40

**Comment by SchrodingersGat** [comment]
Please fix this for all offending _Edge connectors and we should be ok to merge.

**Comment by Matyro** [comment]
Should i add small extensions left and right to match the ends to some sort of grid?
Alternative i could add the coordinares to some layer as text

**Comment by SchrodingersGat** [comment]
A grid would be a really good idea. I'd suggest 0.25mm.

No need for any further text that will just clutter it.

**Comment by Matyro** [comment]
Here is an image with 2.54mm grid but .25 should be better 
unbenannt

**Comment by Matyro** [comment]
Didn't double check something is still wrong

**Comment by Matyro** [comment]
Now its fixed, the little wings are at least 0.25mm long and at max 0.5mm

Following script is used to calculate the next coordinate on the grid:
 nextGrid = math.ceil((K[n]/2.0)/0.25 + 1.0) * 0.25

Vertical its fixed on -5.00mm over the center point, the bottom line is +5mm over the center point

**Comment by SchrodingersGat** [comment]
Great, this looks much better.

Sorry one final thing I have noticed, just a tweak regarding naming:

`_Edge` is capitalized, so `_socket` should become `_Socket` :)

**Comment by Matyro** [comment]
Windows didn't like changes to capitalization but my linux system worked fine

Where should i upload the python scripts for creating the footprints if someone want to change them in future?

**Comment by SchrodingersGat** [comment]
I would suggest https://github.com/pointhi/kicad-footprint-generator

**Comment by SchrodingersGat** [comment]
Thanks for this great contribution :)

**Pull request merged**
