### PR TITLE
Added samtec TSM SMD header connectors

### PR DESCRIPTION
**Pull request by Frankkkkk**
Added some samtec SMD connectors (screenshot below). These are like:
samtec_TSM

Following the [datasheet](http://www.farnell.com/datasheets/2186767.pdf) they can go up to 36×2 pins. I only generated 5 first. If its okay I will push the whole 36.

A question though: Is this good here or should it be put into the **Pin_Headers** package ?
Should I name them too **2x03** in addition to **TSM-103** ?
I superposed the Fab and SilkScreen layers. I don't really know what's the use of the Fab layer ? Should I differentiate them ?

Thanks !

2017-01-24-122531_892x462_scrot

### CODE REVIEW

**Comment by jkriege2** [comment]
Hhmmm ... maybe it would be better to have those in PinHeaders. But then it would be good to have a complete set and best generated by a script ... I can look into this maybe this evening and will come back to you on that!

Best,
JAN

**Comment by Frankkkkk** [comment]
I've attached the script if it can help you.
Thanks,

Frank

**Comment by jkriege2** [comment]
How about this set of pinheaders: https://github.com/KiCad/Pin_Headers.pretty/pull/18

best,
JAN

**Comment by SchrodingersGat** [comment]
Now that https://github.com/KiCad/Pin_Headers.pretty/pull/18 has been merged, is this one OK to close?

**Comment by Frankkkkk** [comment]
Fine by me. Thanks !

**Pull request closed without merging**
