### PR TITLE
ESQ Series double row (+RasPi HAT connector)

### PR DESCRIPTION
**Pull request by theCyanEYED**
From ESQ-101-xx-x-D to ESQ-136-xx-x-D

RasPi connector is an upside-down ESQ-120-xx-x-D following the 40-pin GPIO pin count. It can be used to make Raspberry Pi A+/B+/2(/3?) HATs
**EDIT**: [Datasheet here](http://suddendocs.samtec.com/catalog_english/esq_th.pdf)

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: ESQ-136-xx-x-D
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

You can use the kicad-library-utils to run basic checks.

Also could you please tell me, why you only used one copper layer for the connector?

**Comment by evanshultz** [comment]
@theCyanEYED Will you be able to review the comments above and finish this PR soon?

**Comment by poeschlr** [comment]
I wanted to close/reopen to get travis to check this request. Sadly the original poster seems to have deleted his branch or even fork. (I would guess they are no longer interested in contributing.)

**Comment by evanshultz** [comment]
@poeschlr Thank you! I'll take a look at this and submit a new PR, just to close this issue and get the part merged, if the OP doesn't respond in a couple days.

**Comment by evanshultz** [comment]
@theCyanEYED 
Since I haven't seen a response from you, I'll submit a new PR for this footprint soon which will allow this original PR to be closed. Thanks for generating the initial footprint that will enhance KiCad's library.

**Pull request closed without merging**
