### PR TITLE
SDL and SL series

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added footprints for [SL](https://www.samtec.com/products/sl) and [SDL](https://www.samtec.com/products/sdl) series socket strips

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work .... but judging by the catalog http://suddendocs.samtec.com/catalog_english/sl.pdf ... should the holes be smaller? As I see it the lower parts of the pins are 0.51-0.76mm in dimater ... so a 1-1.1mm hole should be more than sufficient? But your drills are 1.4mm ...

Best,
JAN

**Comment by SchrodingersGat** [comment]
Good spot Jan, I have fixed this now. Reduced drill size to 0.85mm which will accommodate pins for all variants

**Comment by jkriege2** [comment]
Hi! 0.85mm seems very close to 0.76mm ... maybe use 0.95mm then there are at least ~0.1mm on each side of the pin? Does Samtec give any hints what they propose for drills? I didn't see anything in the DS ...

cu
JAN

**Comment by SchrodingersGat** [comment]
I can't seem to find that info either. 0.95mm should be sufficient for all cases. I have updated the pad sizes.

**Comment by jkriege2** [comment]
nice work!
JAN

**Pull request merged**
